<?php
// This code opens a connection to the database, acquires the inputed value and
// inserts a tag into the database tag table with the input as the tag name.

// Include the login information stored in the db_config.php file.
require '../../includes/db_config.php';

// Create connecton using required DEFINEs
$conn = new mysqli(DB_SERVER, DB_USER, DB_PASSWORD, DB_DATABASE);

// Check connection (from w3schools website)
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Get the JSON struct and decode it.
$data = json_decode(file_get_contents('php://input'), true);
echo $data['tag'];

// Insert the provided name of the tag into the database. ID is autogenerated.
mysqli_query($conn, "INSERT INTO tags (tag) VALUES ('".$data['tag']."')") or die(mysqli_error($conn));
?>
